---
server:
  port: 8888
security:
  basic:
    enabled: true
  user: 
    name: amcginlay
    password: password123
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/amcginlay/springcloud-config
          #username: abc
          #password: xyz
          search-paths:
            - "station*"
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/amcginlay/springcloud-config-perf
              search-paths:
                - "station*"
                
  